### PR TITLE
dfuzzer: rework df_print_process_info() a bit

### LINKED ISSUE #8: dfuzzer seems to fail under Valgrind
As far as I can tell it calls `readlink` (which doesn't append terminating null bytes) to get the names of processes and then passes those buffers to strcmp:
```sh
[SYSTEM  BUS]
[PROCESS: /usr/lib/systemd/systemd-resolved

Thread 1 "dfuzzer" hit Breakpoint 1, df_print_process_info (pid=<optimized out>) at dfuzzer.c:971
971	                if (strstr(name, "python") != NULL || strstr(name, "perl") != NULL) {
(gdb) p name
$1 = "/usr/lib/systemd/systemd-resolved [\000;36m[SYSTEM  BUS]\033[0m\n", '\000' <repeats 3438 times>...
```
Below is the backtrace produced by valgrind:
```sh
$ valgrind --track-origins=yes ./dfuzzer -n org.freedesktop.resolve1
==1394== Memcheck, a memory error detector
==1394== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1394== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1394== Command: ./dfuzzer -n org.freedesktop.resolve1
==1394==
[SESSION BUS]
Error: The connection does not exist.
[SYSTEM  BUS]
[PROCESS: /usr/lib/systemd/systemd-resolved
==1394== Conditional jump or move depends on uninitialised value(s)
==1394==    at 0x484F369: strstr (vg_replace_strmem.c:1772)
==1394==    by 0x4031B9: df_print_process_info (dfuzzer.c:971)
==1394==    by 0x4027DE: main (dfuzzer.c:211)
==1394==  Uninitialised value was created by a stack allocation
==1394==    at 0x40305A: df_print_process_info (dfuzzer.c:926)
==1394==
==1394== Conditional jump or move depends on uninitialised value(s)
==1394==    at 0x484F372: strstr (vg_replace_strmem.c:1772)
==1394==    by 0x4031B9: df_print_process_info (dfuzzer.c:971)
==1394==    by 0x4027DE: main (dfuzzer.c:211)
==1394==  Uninitialised value was created by a stack allocation
==1394==    at 0x40305A: df_print_process_info (dfuzzer.c:926)
==1394==
==1394== Conditional jump or move depends on uninitialised value(s)
==1394==    at 0x484F369: strstr (vg_replace_strmem.c:1772)
==1394==    by 0x4031CD: df_print_process_info (dfuzzer.c:971)
==1394==    by 0x4027DE: main (dfuzzer.c:211)
==1394==  Uninitialised value was created by a stack allocation
==1394==    at 0x40305A: df_print_process_info (dfuzzer.c:926)
==1394==
==1394== Conditional jump or move depends on uninitialised value(s)
==1394==    at 0x484F372: strstr (vg_replace_strmem.c:1772)
==1394==    by 0x4031CD: df_print_process_info (dfuzzer.c:971)
==1394==    by 0x4027DE: main (dfuzzer.c:211)
==1394==  Uninitialised value was created by a stack allocation
==1394==    at 0x40305A: df_print_process_info (dfuzzer.c:926)
==1394==
```

### PR DESCRIPTION
**Pull request by mrc0mmand**
to make Valgrind happy.

Fixes: #8

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Looking at the rest of the `df_print_process_info()` function - do we really need the package info stuff? I don't think it's particularly useful, and the code feels quite hackish.

**Comment by mrc0mmand** [comment]
And LGTM seems to agree :-)

**Comment by evverx** [comment]
> do we really need the package info stuff?

I think the idea was to make it easier to report bugs found by `dfuzzer` downstream. I can also imagine a scenario where it could have been used to bisect packages to figure out where bugs were introduced. Given that `systemd-dfuzzer` is supposed to test `systemd` upstream (where changes aren't exactly packaged) I don' think packages are particularly helpful there. I'd go ahead and drop it :-)

File: src/dfuzzer.c [hunk 1]
```diff
@@ -928,54 +928,49 @@ void df_print_process_info(int pid)
...
         FILE *fp;
-        char *c;
         int fd, stdoutcpy, stderrcpy, ret;
 
 
         sprintf(proc_path, "/proc/%d/exe", pid);
         ret = readlink(proc_path, name, sizeof(name));
         // excludes interprets
-        if (ret != -1 && strstr(name, "python") == NULL && strstr(name, "perl") == NULL)
+        if (ret != -1 && !strstr(name, "python") && !strstr(name, "perl")) {
```
Comment (evverx) [inline src/dfuzzer.c]: `name` isn't terminated here so `valgrind` still complains about it:
```sh
$ sudo valgrind ./dfuzzer -v -n org.freedesktop.resolve1
==32298== Memcheck, a memory error detector
==32298== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32298== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==32298== Command: ./dfuzzer -v -n org.freedesktop.resolve1
==32298==
Suppressions from './dfuzzer.conf'
[SESSION BUS]
Session bus not found.
[SYSTEM  BUS]
==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484F369: strstr (vg_replace_strmem.c:1772)
==32298==    by 0x4032C1: df_print_process_info (dfuzzer.c:937)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484F372: strstr (vg_replace_strmem.c:1772)
==32298==    by 0x4032C1: df_print_process_info (dfuzzer.c:937)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484F369: strstr (vg_replace_strmem.c:1772)
==32298==    by 0x403486: df_print_process_info (dfuzzer.c:937)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484F372: strstr (vg_replace_strmem.c:1772)
==32298==    by 0x403486: df_print_process_info (dfuzzer.c:937)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484A608: strlen (vg_replace_strmem.c:494)
==32298==    by 0x4C526C7: __vfprintf_internal (in /usr/lib64/libc.so.6)
==32298==    by 0x4C52E8E: buffered_vfprintf (in /usr/lib64/libc.so.6)
==32298==    by 0x4CFF892: __fprintf_chk (in /usr/lib64/libc.so.6)
==32298==    by 0x4034F9: fprintf (stdio2.h:105)
==32298==    by 0x4034F9: df_print_process_info (dfuzzer.c:938)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32298== Syscall param write(buf) points to uninitialised byte(s)
==32298==    at 0x4CE184F: write (in /usr/lib64/libc.so.6)
==32298==    by 0x4C6569C: _IO_file_write@@GLIBC_2.2.5 (in /usr/lib64/libc.so.6)
==32298==    by 0x4C64A15: new_do_write (in /usr/lib64/libc.so.6)
==32298==    by 0x4C65D6D: _IO_file_xsputn@@GLIBC_2.2.5 (in /usr/lib64/libc.so.6)
==32298==    by 0x4C52EFD: buffered_vfprintf (in /usr/lib64/libc.so.6)
==32298==    by 0x4CFF892: __fprintf_chk (in /usr/lib64/libc.so.6)
==32298==    by 0x4034F9: fprintf (stdio2.h:105)
==32298==    by 0x4034F9: df_print_process_info (dfuzzer.c:938)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==  Address 0x1ffeffc0f3 is on thread 1's stack
==32298==  in frame #4, created by buffered_vfprintf (???:)
==32298==
[PROCESS: /usr/lib/systemd/systemd-resolved[SYSTEM  BUS]

==32298== Conditional jump or move depends on uninitialised value(s)
==32298==    at 0x484A608: strlen (vg_replace_strmem.c:494)
==32298==    by 0x4C526C7: __vfprintf_internal (in /usr/lib64/libc.so.6)
==32298==    by 0x4C5C653: __vsprintf_internal (in /usr/lib64/libc.so.6)
==32298==    by 0x4CFF5B0: __sprintf_chk (in /usr/lib64/libc.so.6)
==32298==    by 0x4035B4: sprintf (stdio2.h:38)
==32298==    by 0x4035B4: df_print_process_info (dfuzzer.c:1006)
==32298==    by 0x4027DE: main (dfuzzer.c:211)
==32298==
==32302== Syscall param execve(argv[i]) points to uninitialised byte(s)
==32302==    at 0x4CBD96B: execve (in /usr/lib64/libc.so.6)
==32302==    by 0x4CE0331: __spawni_child (in /usr/lib64/libc.so.6)
==32302==    by 0x4CF18E3: clone (in /usr/lib64/libc.so.6)
==32302==  Address 0x1ffefff239 is on thread 1's stack
==32302==
[PACKAGE:
```

Comment (mrc0mmand) [reply src/dfuzzer.c]: *d'oh!*, thanks! Even though it was the first thing I wanted to fix, I managed to miss it :-)

File: src/dfuzzer.c [hunk 2]
```diff
@@ -926,120 +926,53 @@ void df_print_process_info(int pid)
...
-                *c = '\0';
-                fprintf(stderr, "%s\n", ansi_normal());
-                close(fd);
+        ret = readlink(proc_path, name, PATH_MAX);
+        if (ret > 0) {
+                if (ret == PATH_MAX) {
+                        df_verbose("The process name was truncated\n");
+                        name[PATH_MAX - 1] = '\0';
+                } else
+                        name[ret] = '\0';
```
Comment (evverx) [inline src/dfuzzer.c]: I think it would be better to declare `name` with `name[PATH_MAX+1]` and then always append a trailing zero byte if `ret >= 0` and (optionally) print the warning if `ret == PATH_MAX`. To me something like
```c
name[PATH_MAX + 1]
ret = readlink(path, name, PATH_MAX)
if (ret >= 0) {
    name[ret] = '\0'
    ...
}
```
is a bit easier to keep track of.

File: src/dfuzzer.c [hunk 3]
```diff
@@ -926,120 +926,53 @@ void df_print_process_info(int pid)
...
 
-                // excludes interprets
-                if (strstr(name, "python") != NULL || strstr(name, "perl") != NULL) {
-                        fprintf(stderr, "%s%s[PACKAGE: %s\n", ansi_cr(), ansi_cyan(), ansi_normal());
+                if (!strstr(name, "python") && !strstr(name, "perl")) {
+                        fprintf(stderr, "%s%s[PROCESS: %s%s\n",
```
Comment (evverx) [inline src/dfuzzer.c]: I know it came from `dfuzzer` but looking at `[PROCESS: /usr/lib/systemd/systemd-resolved` I think either `[` should be removed or `]` should be appended.

Comment (mrc0mmand) [reply src/dfuzzer.c]: Yeah, the same thing is spread across the whole codebase and it's bugging me as well. Not sure what was the original rationale :-)

File: src/dfuzzer.c (hunk 2 above)
Comment (mrc0mmand) [reply src/dfuzzer.c]: That's definitely better, thanks!

**Comment by mrc0mmand** [comment]
Updated, PTAL (and thanks for your patience :-)

File: src/dfuzzer.c [hunk 4]
```diff
@@ -924,122 +924,54 @@ int df_get_pid(const GDBusConnection *dcon)
...
-                fprintf(stderr, "%s%s[PACKAGE: %s\n", ansi_cr(), ansi_cyan(), ansi_normal());
-                // restore std descriptors
-                dup2(stdoutcpy, 1);
-                close(stdoutcpy);
-                dup2(stderrcpy, 2);
-                close(stderrcpy);
-                return;
-        }
+                ret = read(fd, (name + i), 1);
+                if (ret <= 0) {
```
Comment (evverx) [inline src/dfuzzer.c]: I think it should be '<' instead of '<=`. I wonder if this for loop can be replaced with something like
```
ret = read(fd, name, PATH_MAX);
if (ret < 0)
    return;
name[ret] = '\0';
```
it doesn't handle signals and kind of relies on the fact that normally there are zero bytes separating commands and their arguments but I think it's good enough considering that `dfuzzer` isn't supposed to be a mission-critical binary that can be sent to Mars or anything like that.

FWIW the PR looks good to me in its current form so if you think it's good enough feel free to press the merge button. Thanks!

Comment (mrc0mmand) [reply src/dfuzzer.c]: > I think it should be '<' instead of '<=`.

Indeed, thanks!

> I wonder if this for loop can be replaced with something like
> 
> ```
> ret = read(fd, name, PATH_MAX);
> if (ret < 0)
>     return;
> name[ret] = '\0';
> ```
> 
> it doesn't handle signals and kind of relies on the fact that normally there are zero bytes separating commands and their arguments but I think it's good enough considering that `dfuzzer` isn't supposed to be a mission-critical binary that can be sent to Mars or anything like that.
> 

Hehe, yeah, I also wondered if it couldn't be written in a simpler way. I guess I'll keep it there for now and focus on the rest of the code base.

Comment (evverx) [reply src/dfuzzer.c]: > I guess I'll keep it there for now and focus on the rest of the code base.

I think it can be trimmed significantly. For example with https://github.com/systemd/systemd-dfuzzer/commit/798ac0477d1bda1995c386baf8ead2c2d2c311a4 merged I think https://github.com/systemd/systemd-dfuzzer/blob/main/src/remove_escapes.sh can safely be removed. I haven't looked at the C code closely though. The fd and memory leaks vaglrind reports kind of make me avoid it as long as I can but I'll get there I think.
